# Code for training YOLO Segmentation on MOCS dataset
train: "images/train"
val: "images/valid"
test: "images/test"
path: datasets

# nc: 13  # number of classes
names: 
  - Worker
  - Tower Crane
  - Hanging Hook
  - Truck Crane
  - Roller
  - Bulldozer
  - Excavator
  - Truck
  - Loader
  - Pump truck
  - Concrete Truck
  - Pile Driver
  - Other Vehicle
